EventHelper:
  class: Pantono\Core\Events\EventHelper
FilesystemCache:
  class: Pantono\Core\Cache\Factory\FilesystemCacheFactory
  parameters:
    - $cache.path
Twig:
  class: Pantono\Core\Factory\TwigFactory
  parameters:
    - $twig.path
    - $twig.options
